{{ if .Values.app.isValidator }}
apiVersion: v1
kind: Pod
metadata:
  labels:
    "app.kubernetes.io/name": '{{ .Chart.Name }}'
    "app.kubernetes.io/release": "{{ .Release.Name }}"
spec:

{{- end }}
