{{ if $.Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Chart.Name }}
spec:
  podMetricsEndpoints:
    - interval: 5s
      port: node-prom-stats
      path: /metrics
  jobLabel: {{ .Chart.Name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
