apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secrets
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
type: Opaque
data:
  {{- range $key, $val := $.Values.app.envSecrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
