apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-nodeport

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-nodeport
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-nodeport
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-nodeport
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-nodeport
    namespace: {{ .Release.Namespace }}
